### ISSUE TITLE
Detected as malicious software after upgrade to version 2.0.20.0

### ISSUE THREAD

**Issue by wglastonio** [hereafter/mouse-spotlight#3]
Detected as malicious software after upgrade to version 2.0.20.0

Message:
CrowdStrike Falcon Sensor
A process was terminated because malicious software was detected.

**Comment by hereafter** [comment]
Hi, may i know what virus protection software you are using?
This is a false positive, you may need to make an exception from that reporting software.

**Comment by wglastonio** [comment]
Hi,
This problem is cause in an laptop that uses Symantec. And the agent called CrowdStrike Falcon Sensor is blocking.

**Comment by wglastonio** [comment]
Hi,
I was wondering if have some update about this issue.
If not, is there someway to roll back the previous version, please? I really need the app working.
Thanks

**Comment by hereafter** [comment]
Rolling back to an older version is not an option since Windows store does not support that.

I have never used CrowdStrike Falcon sensor before, it looks like some cloud based anti-virus engine.

The engine is making a false positive detection.
The best i could suggest is to 

https://help.redcanary.com/hc/en-us/articles/4413344754071-How-to-Create-Exclusions-in-CrowdStrike-

add exceptions to that engine. 

 
The reason it detects it as a malware,  could be the new 2.0 mouse spotlight uses some undocumented api to render "spotlight" on top of all ui layers, (like lock screen and other staff)



Or are you able to temporary disable the anti-software?

**Comment by wglastonio** [comment]
Hi,
Could you please share this API? So, I could justify internally this is not a real security risk.
Thanks!

**Comment by hereafter** [comment]
sure, the api in question is

SetWindowBand, more details here:
https://blog.adeltax.com/window-z-order-in-windows-10/

**Comment by indonemesis** [comment]
This is the detection in Falcon CS : 

"Description:

A file appears to be imitating a standard OS or otherwise benign filename and/or launched from an unusual location. This might be to masquerade malware."

Anything to explain this behaviour?

Program Files\WindowsApps\25510Hereafter2.MouseSpotlight_2.0.20.0_x64__j2gmvb2kv935w\mouse-spotlight-service

**Comment by wglastonio** [comment]
Hi,
My security team didn't approve to use this app. Is there some modification you could do, please?
I accept you roll back to the previous version.
Thanks,

**Comment by hereafter** [comment]
i guess could build a special version for you without stay on top of all other ui layers. i will get you posted. @wglstonio

**Comment by hereafter** [comment]
> mouse-spotlight-service

@indonemesis

this is the process which actually renders the spotlight. In order for it to render on top of all other ui, start menu/taskbar/any other software, it will use an undocument api


SetWindowBand, more details here:
https://blog.adeltax.com/window-z-order-in-windows-10/

this gate keeper needs to update their database to valildate if it is a false-postive. let them know please.

It passes windows store validation :) for secure measures

**Comment by hereafter** [comment]
@wglastonio 

I have posted an update to the Windows Store , please download the newer version, and use the last "System-wide Topmost" toggle to see if it helps

**Comment by wglastonio** [comment]
Hi @hereafter ,
I updated the version, but the application is still being blocked by CrowdStrike Falcon Sensor. It detects the Mouse Spotlight as a threat.
:(
Hope you could help on that.

**Comment by hereafter** [comment]
have you tried turn off the last toggle?

![image](https://user-images.githubusercontent.com/1483954/156494015-461f9267-268f-4c45-b8a5-0f044c5064de.png)


could you have some screenshot or capture to show what happens exactly?

**Comment by wglastonio** [comment]
wow man, I'm sorry! I didn't get that.

After change the configuration you've mentioned it worked. Lost some features, but OK! ;)

Thanks a lot for your support.
